# Generated by Django 3.0.7 on 2020-06-23 21:21

from django.db import migrations, models

import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_city",
            field=models.TextField(blank=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address_line_1",
            field=models.TextField(blank=True, verbose_name="Address line 1"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_line_2",
            field=models.TextField(blank=True, verbose_name="Address line 2"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_postcode",
            field=models.TextField(blank=True, verbose_name="Postcode"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_state",
            field=models.TextField(blank=True, verbose_name="State"),
        ),
    ]
