# Generated by Django 3.0.7 on 2020-06-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0002_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("drawn", models.DateTimeField()),
                ("sent", models.DateTimeField()),
                ("received", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="exchanges",
            field=models.ManyToManyField(to="af_gang_mail.Exchange"),
        ),
    ]
