# Generated by Django 3.0.7 on 2020-06-26 14:56

from django.db import migrations

import autoslug.fields


def save_all_exchanges(apps, schema_editor):
    """By saving all exchanges we automatically generate a slug."""

    Exchange = apps.get_model("af_gang_mail", "Exchange")
    for exchange in Exchange.objects.all():
        exchange.save()


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0004_draws"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.RunPython(save_all_exchanges),
        migrations.AlterField(
            model_name="exchange",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
