# Generated by Django 3.0.7 on 2020-06-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0005_exchange_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="draw",
            constraint=models.UniqueConstraint(
                fields=("exchange", "sender"), name="send_once_per_exchange"
            ),
        ),
        migrations.AddConstraint(
            model_name="draw",
            constraint=models.UniqueConstraint(
                fields=("exchange", "recipient"), name="receive_once_per_exchange"
            ),
        ),
    ]
