# Generated by Django 3.0.8 on 2020-07-03 22:19

from django.db import migrations


def create_flatblock(apps, schema_editor):
    """Create home-unverified-email-address flat block."""

    FlatBlock = apps.get_model("flatblocks", "FlatBlock")
    if not FlatBlock.objects.filter(slug="home-unverified-email-address").exists():
        FlatBlock.objects.create(
            slug="home-unverified-email-address",
            header="In order to participate in exchanges, you need to verify your email address.",
            content=(
                "<p>We sent you an e-mail when you signed up with instructions on how to do "
                "this.</p>"
                "<p>If you haven't received this email check your spam folder, or "
                "<a href='/resend-verification'>request another email</a>.</p>"
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0006_draw_constraints"),
        ("flatblocks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_flatblock),
    ]
