# Generated by Django 3.0.8 on 2020-07-04 09:56

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace


def fix_email_spelling(apps, schema_editor):
    """By saving all exchanges we automatically generate a slug."""

    FlatBlock = apps.get_model("flatblocks", "FlatBlock")
    FlatBlock.objects.update(header=Replace("header", Value("e-mail"), Value("email")))
    FlatBlock.objects.update(header=Replace("header", Value("E-mail"), Value("Email")))
    FlatBlock.objects.update(
        content=Replace("content", Value("e-mail"), Value("email"))
    )
    FlatBlock.objects.update(
        content=Replace("content", Value("E-mail"), Value("Email"))
    )


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0007_email_verification"),
    ]

    operations = [
        migrations.RunPython(fix_email_spelling),
    ]
