# Generated by Django 3.0.8 on 2020-07-03 22:19

from django.db import migrations


def create_flatblock(apps, schema_editor):
    """Create confirm-email-intro flat block."""

    FlatBlock = apps.get_model("flatblocks", "FlatBlock")
    if not FlatBlock.objects.filter(slug="confirm-email-intro").exists():
        FlatBlock.objects.create(
            slug="confirm-email-intro",
            header="Confirm Email Address",
            content="",
        )

    if not FlatBlock.objects.filter(slug="confirm-email-already-used").exists():
        FlatBlock.objects.create(
            slug="confirm-email-already-used",
            header="Confirm Email Address",
            content=(
                "<p>This email confirmation link has expired or is invalid.</p>"
                "<p><a href='/resend-verification'>Send a new verification email.</a></p>"
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0008_email_spelling"),
    ]

    operations = [
        migrations.RunPython(create_flatblock, migrations.RunPython.noop),
    ]
