# Generated by Django 3.0.8 on 2020-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0009_confirm_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="draw_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
