# Generated by Django 3.0.8 on 2020-07-06 21:20

from django.db import migrations


def create_flatblock(apps, schema_editor):
    """Create draw-intro flat block."""

    FlatBlock = apps.get_model("flatblocks", "FlatBlock")
    if not FlatBlock.objects.filter(slug="draw-intro").exists():
        FlatBlock.objects.create(
            slug="draw-intro", header="Draw Details", content="",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('af_gang_mail', '0010_exchange_draw_started'),
    ]

    operations = [
        migrations.RunPython(create_flatblock, migrations.RunPython.noop),
    ]
