# Generated by Django 3.0.8 on 2020-07-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0011_draw_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="send_emails",
            field=models.BooleanField(default=False),
        ),
    ]
