# Generated by Django 3.0.8 on 2020-07-11 14:56

from django.db import migrations


def create_flatblock(apps, schema_editor):
    """Create home-no-name flat block."""

    FlatBlock = apps.get_model("flatblocks", "FlatBlock")
    if not FlatBlock.objects.filter(slug="home-no-name").exists():
        FlatBlock.objects.create(
            slug="home-no-name",
            header="In order to participate in exchanges, you need to enter your name.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0012_exchange_send_emails"),
    ]

    operations = [
        migrations.RunPython(create_flatblock, migrations.RunPython.noop),
    ]
