# Generated by Django 3.0.8 on 2020-07-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0013_no_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user", options={"permissions": [("statto", "Can view statto")]},
        ),
    ]
