# Generated by Django 3.0.8 on 2020-07-12 11:43

from django.db import migrations


def create_flatblock(apps, schema_editor):
    """Create home-short-address flat block."""

    FlatBlock = apps.get_model("flatblocks", "FlatBlock")
    if not FlatBlock.objects.filter(slug="home-short-address").exists():
        FlatBlock.objects.create(
            slug="home-short-address",
            header="Have you entered your address?",
            content=(
                "<p>It looks like your address is pretty short. Someone might have trouble "
                "sending you a gift. Are you sure you have entered it correctly?</p>"
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0013_no_name"),
    ]

    operations = [
        migrations.RunPython(create_flatblock, migrations.RunPython.noop),
    ]
