# Generated by Django 3.0.8 on 2020-07-13 18:18

from django.db import migrations

import af_gang_mail.models


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0014_statto"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", af_gang_mail.models.UserManager()),],
        ),
    ]
