# Generated by Django 3.0.8 on 2020-07-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0015_user_manager"),
        ("af_gang_mail", "0014_short_address"),
    ]

    operations = []
