# Generated by Django 3.0.8 on 2020-07-25 14:18

from django.db import migrations, models


def combine_lines(apps, schema_editor):
    """Combine address lines."""

    User = apps.get_model("af_gang_mail", "User")
    for user in User.objects.all():
        address_lines = [user.address_line_1, user.address_line_2]
        user.street_address = "\n".join([line for line in address_lines if line])
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0016_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="street_address",
            field=models.TextField(blank=True, verbose_name="Street Address"),
        ),
        migrations.RunPython(combine_lines, migrations.RunPython.noop),
        migrations.RemoveField(model_name="user", name="address_line_1",),
        migrations.RemoveField(model_name="user", name="address_line_2",),
    ]
