# Generated by Django 3.1 on 2020-08-05 12:32

from django.db import migrations

TITLE = "Privacy & Data Security"
CONTENT = (
    "<p>We collect and store:</p>\r\n"
    "<ul>\r\n"
    "\t<li><strong>Your email address</strong> "
    "so that we can send you notifications and log you in.</li>\r\n"
    "\t<li><strong>Your password</strong> "
    'so that we can identify you. <a href="'
    "https://docs.djangoproject.com/en/stable/topics/auth/passwords/"
    '#how-django-stores-passwords">This password is securely hashed</a>.</li>\r\n'
    "\t<li><strong>Your name and address</strong> "
    "so that other users can send you gifts.</li>\r\n"
    "</ul>\r\n"
    "\r\n"
    "<p>This information is stored in a PostgreSQL database hosted by "
    '<a href="https://www.heroku.com/policy/security">Heroku</a>. '
    "Emails containing your name and address are sent using "
    '<a href="https://help.sendinblue.com/hc/en-us/sections/'
    '360000396424-Privacy-and-confidentiality-of-your-personal-information">'
    "Sendinblue</a>.</p>\r\n"
    "\r\n"
    "<p>We also track user behaviour using "
    '<a href="https://usefathom.com">Fathom</a>, application performance using '
    '<a href="https://newrelic.com">New Relic</a>,&nbsp;and errors using '
    '<a href="https://sentry.io">Sentry</a>. No personally identifying information '
    "is recorded by those systems.</p>\r\n"
    "\r\n"
    "<p>When you participage in an exchange, your name and address will be shared with "
    "one person. That person will recieve your name and address in an email, and will "
    "be able to view your name and address on the site.</p>\r\n"
    "\r\n"
    "<p><strong>Cookies</strong></p>\r\n"
    "\r\n"
    '<p>We store <a href="'
    'https://docs.djangoproject.com/en/stable/topics/http/sessions/">session ID</a> '
    'and a <a href="https://docs.djangoproject.com/en/stable/ref/csrf/">cross-site '
    "request forgery (CSRF)</a> cookies in your browser, both of which are required "
    "for the proper functioning of this site.</p>\r\n"
    "\r\n"
    "<p><strong>Controlling Your Data</strong></p>\r\n"
    "\r\n"
    "<p>You&#39;re able to change your password and edit your name and address via "
    "the web site. If you&#39;d like to change your email address or remove yourself "
    'completely from the site, <a href="http://craiga.id.au">please get in touch '
    "with Craig Anderson</a>.</p>"
)


def create_flatpage(apps, schema_editor):
    """Create privacy flat block."""

    FlatPage = apps.get_model("flatpages", "FlatPage")
    Site = apps.get_model("sites", "Site")
    if not FlatPage.objects.filter(url="/privacy/").exists():
        page = FlatPage.objects.create(
            url="/privacy/",
            title=TITLE,
            content=CONTENT,
        )
        page.sites.set(Site.objects.all())


def create_flatblock(apps, schema_editor):
    """Create privacy flat block."""

    FlatBlock = apps.get_model("flatblocks", "FlatBlock")
    if not FlatBlock.objects.filter(slug="privacy").exists():
        FlatBlock.objects.create(
            slug="privacy",
            header=TITLE,
            content=CONTENT,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0017_django31"),
        ("flatpages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_flatpage, create_flatblock),
    ]
