# Generated by Django 3.1 on 2020-08-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0019_draw_sent_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="draw",
            name="sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
