# Generated by Django 3.1 on 2020-09-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0020_draw_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="draw",
            name="received",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
