# Generated by Django 3.1.3 on 2020-12-13 13:56

from django.db import migrations, models
from django.utils.timezone import now


def set_reminder_started(apps, schema_editor):
    """Set reminder started fields."""

    Exchange = apps.get_model("af_gang_mail", "Exchange")

    for exchange in Exchange.objects.filter(sent__lt=now()):
        exchange.send_reminder_started = now()
        exchange.save()

    for exchange in Exchange.objects.filter(received__lt=now()):
        exchange.receive_reminder_started = now()
        exchange.save()


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0021_draw_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="receive_reminder_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exchange",
            name="send_reminder_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_reminder_started, migrations.RunPython.noop),
    ]
