# Generated by Django 3.1.4 on 2021-01-20 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("af_gang_mail", "0022_reminders_started"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE af_gang_mail_user_exchanges RENAME TO af_gang_mail_userinexchange",
                    reverse_sql="ALTER TABLE af_gang_mail_userinexchange RENAME TO af_gang_mail_user_exchanges",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="UserInExchange",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "exchange",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="users_in_exchange",
                                to="af_gang_mail.exchange",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="user_in_exchanges",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="user",
                    name="exchanges",
                    field=models.ManyToManyField(
                        related_name="users",
                        through="af_gang_mail.UserInExchange",
                        to="af_gang_mail.Exchange",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userinexchange",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exchange",
            name="confirmation",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="exchange",
            name="confirmation_reminder",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="exchange",
            name="confirmation_reminder_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exchange",
            name="confirmation_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
