name: Python
on:
  push:
    paths:
      - "**/*.py"
      - ".github/workflows/python.yaml"
      - "Makefile"
      - "Pipfile.lock"

jobs:
  lint-python:
    name: Lint Python Code
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2.3.4
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Lint Python Code
        run: make lint-python
        env:
          DJANGO_SETTINGS_MODULE: af_gang_mail.settings
