name: SCSS
on:
  push:
    paths:
      - "**/*.scss"
      - ".github/workflows/scss.yaml"
      - "Makefile"
      - "package-lock.json"

jobs:
  lint-scss:
    name: Lint SCSS
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 12
      - name: Setup
        run: npm install prettier@`cat package-lock.json | jq ".dependencies.prettier.version" --raw-output`
      - name: Lint SCSS
        run: make lint-scss
