name: YAML
on:
  push:
    paths:
      - "**/*.yaml"
      - ".github/workflows/yaml.yaml"
      - "Makefile"
      - "package-lock.json"

jobs:
  lint-yaml:
    name: Lint YAML
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 12
      - name: Setup
        run: npm install prettier@`cat package-lock.json | jq ".dependencies.prettier.version" --raw-output`
      - name: Lint YAML
        run: make lint-yaml
